apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-usertest
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: my-spark-with-s3a:s3
  imagePullPolicy: IfNotPresent
  mainClass: fr.umontpellier.polytech.UserTest
  mainApplicationFile: s3a://spark/scala-project_2.12-1.0.jar
  arguments:
  - "5000"
  sparkVersion: 3.5.3
  driver:
    labels:
      version: 3.5.3
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    labels:
      version: 3.5.3
    instances: 1
    cores: 1
    memory: 512m
  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "http://myminio-hl.minio-tenant.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.access.key": "DgNpMIDsKt4ZDJW6q2EK"
    "spark.hadoop.fs.s3a.secret.key": "0yZY2laZurpLcW3cGaZqU7SH0Ez8e6BnysP8IKwU"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    "spark.driver.extraClassPath": "/opt/spark/jars/*"
    "spark.executor.extraClassPath": "/opt/spark/jars/*"